### ISSUE TITLE
cleanup-empty-dates issue

### ISSUE THREAD

**Issue by talek** [akirak/org-reverse-datetree#11]
Hello,

I've just discovered your package and I was playing around with it. Great job, btw!
Then I've come across the `cleanup-empty-dates`, but for my file it doesn't seem to work:

```
#+TITLE: Daily Life
* 2020
** 2020-11 November
*** 2020-11-22 Sunday
```

When I invoke the cleanup function, I simply get the message: No trees were deleted. Aborting. Wasn't it supposed that everything to cleanup nicely?

Also, have you consider refactoring this function so that to be possible to invoke it in an unattended way. I'd love to use it like:

```
(advice-add 'org-archive-subtree :after #'org-reverse-datetree-cleanup-empty-dates)
```

Thanks!

**Comment by akirak** [comment]
Thank you for reaching out the issue. I will look into it soon. Could you show me an example (with the configuration header) where the cleanup function didn't work? 

For advising `org-archive-subtree`, I think it's an excellent idea, but it can mess up non-datetree files. It will need another function that wraps the cleanup function.

```elisp
(advice-add 'org-archive-subtree :after #'org-reverse-datetree-cleanup-empty-dates)
```

**Comment by talek** [comment]
Interestingly enough, the configuration header was not generated for the file from my example. The configuration I use is:

```
(use-package! org-reverse-datetree
  :config
  (setq-default org-reverse-datetree-level-formats
                '("%Y"                    ; year
                  (lambda (time) (format-time-string "%Y-%m %B" (org-reverse-datetree-monday time))) ; month
                  "%Y-%m-%d %A"           ; date
                  )))
```

And you're right about advising the `org-arhive-subtree`... A more clever way of doing it is needed to avoid messing up other non-datatree files. I've overlooked this part.

**Comment by akirak** [comment]
@talek I think I've fixed the issue. If there is something wrong with the feature, please report the issue again. Thanks.
