### ISSUE TITLE
Overwrite init settings 

### ISSUE THREAD

**Issue by rbenson** [akirak/org-reverse-datetree#17]
I have 
    org-reverse-datetree-level-formats '("%Y"                    ; year
 				      (lambda (time) (format-time-string "%Y-%m %B" (org-reverse-datetree-monday time))) ; month
 				      "%Y %B W%W"                ; week
 				      "%Y-%m-%d %A"           ; date
 				      )

in my .emacs. I have another org file where I don't need to track the week, so I have the following in the header of a file I don't use much

#+REVERSE_DATETREE_DATE_FORMAT: %Y-%m-%d %A
#+REVERSE_DATETREE_MONTH_FORMAT: %Y-%m %B
#+REVERSE_DATETREE_YEAR_FORMAT: %Y
#+REVERSE_DATETREE_USE_WEEK_TREE: nil

but the week is still inserted. I thought I tried a local variable, but it isn't taking.

**Comment by akirak** [comment]
The variable `org-reverse-datetree-level-formats` takes precedence over the settings in the file header. Thus you have two options:

- Set the variable (as a local variable) only in the file(s) you want to apply the setting.
- Set the variable to nil in the file you don't want to apply the setting.

**Comment by rbenson** [comment]
For the second option, what would that look like? Using `add-file-local-variable-prop-line`, no variables from this package are populated in helm.

**Comment by akirak** [comment]
> Using add-file-local-variable-prop-line, no variables from this package are populated in helm.

Maybe you have to load `org-reverse-datetree` explicitly before you run the command. It's shown at least in my environment.

Alternatively, my [org-starter](https://github.com/akirak/org-starter) package allows you to configure file-local variables as follows:

```emacs-lisp
(org-starter-def "projects.org"
  :key "P"
  :local-variables
  ((org-reverse-datetree-level-formats
    . ("Weekly journal"
       "%Y"
       "%Y W%W (%b %e)"))))
```

**Comment by rbenson** [comment]
Calling `load-package`, then the `prop-line` allows it to propagate.

I have elected to put a Level 1 headline at the end of the file named Local Variables.

Side note, you  may want to mention enabling `reveal-mode` is helpful when using `org-reverse-datetree-goto-date-in-file`
