### ISSUE TITLE
Is there a way to create entries for a range of dates?

### ISSUE THREAD

**Issue by vonpupp** [akirak/org-reverse-datetree#18]
Hello,

I just stumbled upon this package and I am excited since it seems that is going to be very helpful to me.

I usually plan my week on sundays. Having to select each day to create an entry 7 times is doable. However, I was wondering if there is a way to automate this for a date range. I am not fluent at all in lisp, but from what I understood it should be something like (python like pseudo-code):
```
for <date> in range(<start_date>, <end_date>):
    org-reverse-datetree-goto-date-in-file(<date>)
```

Does that makes sense? Any suggestion? Thank you very much.

**Comment by akirak** [comment]
Hello @vonpupp, thank you for your compliment.

Yes, your code would work, but it is suboptimal in terms of performance.

Alternatively, you can generate the parent tree using `org-reverse-datetree-2` and insert date trees as follows, which would be  faster but with more code:

```emacs-lisp
(let ((start-day (current-time)))
  (org-reverse-datetree-2 start-day
                          '("%Y"
                            "%Y %W")
                          nil)
  (dolist (n (number-sequence 6 0 -1))
    (insert "\n*** "
            (format-time-string "%Y-%m-%d" (time-add start-day (* n 86400))))))
```

**Comment by vonpupp** [comment]
Thank you very much! I will give that a try and reopen if necessary.
