### ISSUE TITLE
%W can start on 1 instead of 0?

### ISSUE THREAD

**Issue by vonpupp** [akirak/org-reverse-datetree#19]
Hello again,

I am using a config as follows:
```
#+REVERSE_DATETREE_DATE_FORMAT: [DAILY] %Y-%m-%d %a
#+REVERSE_DATETREE_WEEK_FORMAT: [DAILY] %Y-W%W
#+REVERSE_DATETREE_YEAR_FORMAT: [DAILY] %Y
```

So it yields something like this:
```
* [DAILY] 2022
** [DAILY] 2022-W01
*** [DAILY] 2022-01-08 Sat
*** [DAILY] 2022-01-07 Fri
*** [DAILY] 2022-01-06 Thu
*** [DAILY] 2022-01-05 Wed
*** [DAILY] 2022-01-04 Tue
*** [DAILY] 2022-01-03 Mon
** [DAILY] 2022-W00
*** [DAILY] 2022-01-02 Sun
*** [DAILY] 2022-01-01 Sat
```

Everything works as expected except that the week number starts with 0 instead of 1, I am not sure if this is something emacs related or if it is something related to this module. Ideally I would like week numbers to match the output of `cal -yw` as follows:
```
                                    2022                                   

        January                   February                   March         
   Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa      Su Mo Tu We Th Fr Sa
 1                    1    6        1  2  3  4  5   10        1  2  3  4  5
 2  2  3  4  5  6  7  8    7  6  7  8  9 10 11 12   11  6  7  8  9 10 11 12
 3  9 10 11 12 13 14 15    8 13 14 15 16 17 18 19   12 13 14 15 16 17 18 19
 4 16 17 18 19 20 21 22    9 20 21 22 23 24 25 26   13 20 21 22 23 24 25 26
 5 23 24 25 26 27 28 29   10 27 28                  14 27 28 29 30 31      
 6 30 31
```

EDIT: I tried with %V and %U but none of them seem to work as expected.

Output of %U: (note week W00, when it should start on 01 according to [this])
```
* [DAILY] 2022
** [DAILY] 2022-W01
*** [DAILY] 2022-01-02 Sun
** [DAILY] 2022-W00
*** [DAILY] 2022-01-01 Sat
```

Output of %V: (note week W52)
```
* [DAILY] 2022
** [DAILY] 2022-W52
*** [DAILY] 2022-01-02 Sun
*** [DAILY] 2022-01-01 Sat
```

Could you please shed some light on this? Thank you very much.
[this]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Time-Parsing.html

**Comment by akirak** [comment]
org-reverse-datetree uses the built-in `format-time-string` function. The function doesn't seem to provide such an option, so I am sorry to say that it is not feasible in an elegant way.

However, you can [provide a user function](https://github.com/akirak/org-reverse-datetree#configuring-date-formats) to format headlines at a certain level. This is an ugly hack, but you can increment the week number using the following function:

```emacs-lisp
(lambda (time) (format "%02d" (1+ (string-to-number (format-time-string "%W" time)))))
```

**Comment by vonpupp** [comment]
Thank you very much. I thought it was something related to emacs rather than your package. The weird thing is that emacs itself it starts counting on 0. I will dig more into this, since it is weird for theoretically both be following ISO and give different outputs. Probably I am missing something here. I will close this issue and post back if I find anything useful related to this. Thanks again!
