### ISSUE TITLE
Datetree capture under a specific heading

### ISSUE THREAD

**Issue by krvpal** [akirak/org-reverse-datetree#23]
Hi, 

Thank you very much for this excellent package. I use it daily for work and for journals, and can't live without it.

I've tried hard to find a way to make a reverse datetree capture template under a specific heading in a file and couldn't make it work. Would you have any suggestions please? The 'file+function' template is provided as an example, is there something akin to 'file+heading+function' to use reverse datetrees?

This would really help with my workflows if I could capture into two or more datetrees within the same file under different headings. Thanks again for this amazing package.

**Comment by akirak** [comment]
Hello, thanks for your compliment.

Perhaps you could implement your requirement by setting `org-reverse-datetree-level-formats` variable as follows:

```emacs-lisp
(setq-default org-reverse-datetree-level-formats
                '("My Group 1"
                  "%Y"                    ; year
                  (lambda (time) (format-time-string "%Y-%m %B" (org-reverse-datetree-monday time))) ; month
                  "%Y W%W"                ; week
                  "%Y-%m-%d %A"           ; date
                  ))
```

If you were not setting the variable, you can take the value from the file header.

And you can use a `file+function` capture template as documented.

(I'd recommend you back up your file before you try out the setting.)

**Comment by akirak** [comment]
Sorry, I didn't get the answer right.

For multiple groups, you can define functions like this:

```emacs-lisp
(defun my-org-datetree-group-1 ()
  (org-reverse-datetree-2 nil '("My Group 1"
                                "%Y"
                                "%Y W%W"
                                "%Y-%m-%d %A")))
```

**Comment by krvpal** [comment]
Thank you very much for the suggestions. I tried both of the options, sometimes the main heading or group would get created each time I ran a capture template. So, as per the examples above, "My Group 1" would be created multiple times i.e., each time I used the capture template.

Also, the second suggestion threw an error as it needed one last argument. I have used it as below and it does seem to work. It is strange, after a while getting problems with duplicated headings, it started working out of nowhere.
```elisp
(defun my-org-datetree-group-1 ()
  (org-reverse-datetree-2 nil '("My Group 1"
                                "%Y"
                                "%Y W%W"
                                "%Y-%m-%d %A") "point"))
```
                               
If I wanted a datetree to start after deeper than level 1, it seems to not work either. For example, using the below doesn't work:

```elisp
(defun my-org-datetree-group-1 ()
  (org-reverse-datetree-2 nil '("My Group 1"
                                "My Sub-group 1"
                                "%Y"
                                "%Y W%W"
                                "%Y-%m-%d %A") "point"))
```

Is there anyway we can have an easier way to create templates for reverse datetrees under specific headings or subtrees? Something akin to "file+olp+datetree"?

**Comment by akirak** [comment]
> Also, the second suggestion threw an error as it needed one last argument. I have used it as below and it does seem to work. 

Yes, it was mandatory, but I have made it optional recently. I'm sorry for this. Could you upgrade the package to the latest version? Giving a third argument would work anyway.

> I tried both of the options, sometimes the main heading or group would get created each time I ran a capture template. 

> If I wanted a datetree to start after deeper than level 1, it seems to not work either.

This is because the above examples assume the group trees are lexicographically sorted (by descending order). I now understand this assumption would be unrealistic for your use case. 

> Is there anyway we can have an easier way to create templates for reverse datetrees under specific headings or subtrees? Something akin to "file+olp+datetree"?

I think this is feasible by adding an optional argument. Let me consider...

**Comment by akirak** [comment]
I have pushed a commit to `feat/olp` branch. Can you try this? 

First configure the datetree as usual (without the parent olp):

```emacs-lisp
(setq-default org-reverse-datetree-level-formats
                '("%Y"                    ; year
                  (lambda (time) (format-time-string "%Y-%m %B" (org-reverse-datetree-monday time))) ; month
                  "%Y W%W"                ; week
                  "%Y-%m-%d %A"           ; date
                  ))
```

Then call `org-reverse-datetree-goto-date-in-file` with `:olp` option (Note the first argument must be `nil`):

```emacs-lisp
(org-reverse-datetree-goto-date-in-file nil :olp '("Group 1" "Subgroup 1"))
```

**Comment by akirak** [comment]
The feature is now on master. Please send me a feedback if there is any issue with it.

**Comment by krvpal** [comment]
Hi, thank you very much for adding this as a new feature. In my testing so far with a capture template this is working very well. There were yet again some cases where the target subtree was created multiple times, but as you've rightly noted it occurred when the target subtree didn't already exist and wasn't lexicographically arranged.

Possibly, as a suggestion for the future, an idea is to make use of `ids` to find the target first and then create the datetree under it. I will leave this as a mere suggestion.

Lastly, I'm using the below to make sure I'm prompted interactively to choose a date (`org-read-date` section instead of `nil` before `:olp`):
```emacs
(setq org-capture-templates
      '(("c" "Commonplace book" entry
         (file+function "cpb.org"
                        (lambda ()
                          (org-reverse-datetree-goto-date-in-file
                           (org-read-date nil t nil) :olp '("Group" "Subgroup 1"))))
         "* %?"
         :clock-in t :clock-resume t)))
```
Thank you again!

**Comment by akirak** [comment]
Thanks!
