### ISSUE TITLE
Enable months AND weeks structures

### ISSUE THREAD

**Issue by samspo** [akirak/org-reverse-datetree#4]
Hello,
Nice package. I like the reverse datetree organization. 
I'm wondering if it would be possible to offer the possibility to add a level to the datetree in the following way:
```
* Year
** Month
*** Week
**** Day
```
I know it is not possible in the default datetree of orgmode, but I'd like to have this possibility in order to implement something like a bullet journal.

**Comment by akirak** [comment]
Hello,

Thanks for your comment. The current implementation of this package assumes that the date tree consists of three levels. It is not very easy to support date trees consisting of four levels, but it is possible. I will consider adding the feature.

**Comment by samspo** [comment]
Thanks!

**Comment by akirak** [comment]
I've just implemented the feature in [this branch](https://github.com/akirak/org-reverse-datetree/tree/feature/month-and-week). You can try it out right now.

As with the previous version, it prompts for a datetree structure at initial creation. I've chosen the following keys in the prompt, but what do you think of it, especially about `b` (both)? Do you have a better idea?

- `y` (yes) or `w` (week): week tree
- `n` (no) or `m` (month): month tree
- `b` (both): month and week

**Comment by samspo** [comment]
Hello,

Thanks a lot. The keys are perfect.

I have two issues (see a copy) :

1 - when a week belongs to 2 months, it creates two headings for the same week (see the example of week 21)

2 - not specific to this version but sometimes I have blanks before headings and sometime I don't have blanks before headings. I'd like to avoid blanks between headings and n my config, I have
`(setq org-blank-before-new-entry '((heading . nil)
				   (plain-list-item . nil)))`

----------
<img width="513" alt="1" src="https://user-images.githubusercontent.com/1280210/58363329-3577ee80-7e70-11e9-8294-11d956cf92c5.png">

**Comment by akirak** [comment]
> 1 - when a week belongs to 2 months, it creates two headings for the same week (see the example of week 21)

This is because the month is determined based on individual dates, and not based on the start of the week. 

To satisfy your requirement, I've added support for using a function as a format. That is, you can specify a custom function to format dates. In your case, you can use the following month format:

```
#+REVERSE_DATETREE_MONTH_FORMAT: (lambda (time) (format-time-string "%Y-%m %B" (org-reverse-datetree-monday time)))
```

`org-reverse-datetree-monday` is a time-subtracting function that returns last Monday before a particular date. If you prefer week trees starting on Sunday, you can use `org-reverse-datetree-sunday` instead of `org-reverse-datetree-monday`.

This might look weird, but I prefer the flexibility of allowing any function for formatting dates. What do you think? 

> 2 - not specific to this version but sometimes I have blanks before headings and sometime I don't have blanks before headings. I'd like to avoid blanks between headings and n my config, I have
(setq org-blank-before-new-entry '((heading . nil) (plain-list-item . nil)))

I will work on this issue after we finish with the discussion above.

**Comment by samspo** [comment]
I'm not able to make it work, even with the default attributes proposed on a new file.
I also tried it with a clean emacs config with only
```
(use-package  org-reverse-datetree
  :load-path "/Users/sam/.emacs.d/quelpa/build/org-reverse-datetree/org-reverse-datetree.el")

```
I always obtain:
`Wrong number of arguments: #<subr min>, 0
`

**Comment by akirak** [comment]
Sorry about that. I have fixed the error.

**Comment by akirak** [comment]
I also fixed the blank issue. It is available from [this branch](https://github.com/akirak/org-reverse-datetree/tree/feature/blank-before-new-entry). Does it work as expected?

**Comment by samspo** [comment]
The 2 issues are resolved now. It's nice and works as expected. 
I will use that for my journal now.
Thanks a lot!
(another remark, I have no idea of how it is complicated to offer this possibility, but I usually prefer to put the configuration in configurations files instead of the file edited)

**Comment by akirak** [comment]
If you don't mind applying the setting to all files, you can do that by setting `org-reverse-datetree-level-formats` as follows:

```emacs-lisp
(setq-default org-reverse-datetree-level-formats
              '("%Y"                    ; year
                (lambda (time) (format-time-string "%Y-%m %B" (org-reverse-datetree-monday time))) ; month
                "%Y W%W"                ; week
                "%Y-%m-%d %A"           ; date
                ))
```

Thank you for reporting. I will merge it into master soon.

**Comment by samspo** [comment]
Perfect. Thanks!
