### ISSUE TITLE
Ignore part of heading after date format is consumed

### ISSUE THREAD

**Issue by jbarbero1** [akirak/org-reverse-datetree#63]
I love the idea of this package, and am trying to use it with my 10+year old reverse datetree journal file that I've just kept up by hand.

I have many headings that look like:

2024-07-01 - Supreme Court and presidential immunity

If I configure
#+REVERSE_DATETREE_DATE_FORMAT: %Y-%m-%d

then these entries are correctly populated in the calendar view. However, jumping to a date with org-reverse-datetree-display-entry causes a new entry to be created alongside the existing one.

It would be great if org-reverse-datetree could recognize that it has consumed the part matching the date format after 2024-07-01 and recognize that there is a matching entry to the date I requested.

On a related note, it would also be nice if entries didn't have to be lexicographically sorted. I tend to write headings like:

2024 July 1 Mon

and I had to convert all my dates to ISO format to use them with this package.

Let me know if I can help contributing a patch; not sure how easy/hard these two features would be. Thanks!

**Comment by akirak** [comment]
Do you have exactly one journal entry per date, or possibly multiple entries on each date?

> 2024-07-01 - Supreme Court and presidential immunity

This is not how this package is supposed to work. 

Instead, the following convention would work:

```
* 2024-07-01
** Supreme Court and presidential immunity
```

>  if entries didn't have to be lexicographically sorted

This is also not what this package is intended for. If you don't want date trees to be sorted, you can just create an `org-capture` template to file an entry. You also need a calendar support?

If you are okay with the above assumptions, you can convert your journal file to the supported structure, using an Emacs Lisp script:

1. Set `org-reverse-datetree-level-formats` to one-level format (with a single element).
2. Refile each entry to a corresponding date heading.
3. Sort the top-level heading.

Before you start the conversion, don't forget to back up the file (or commit the file to a Git repository, if any).

**Comment by jbarbero1** [comment]
Yes, perhaps this package isn't for me. Shame, as it gets me tantalizingly close to what I want, which is calendar integration for my journal. I checked out this package because org-journal is more opinionated about journal file layouts. I really want a non-opinionated journaling helper. I guess it'll be easier to just write a few elisp functions of my own.

**Comment by akirak** [comment]
Okay, feel free to ask if you get interested in this package again.
