### ISSUE TITLE
file+function+headline  ???

### ISSUE THREAD

**Issue by Aneeqasif** [akirak/org-reverse-datetree#64]
Hi thanks for developing such a nice package i am trying to do something like this but i think its not done the way I am doing it can you please help

```elisp
          ("jw" "weekly Journal")
          ("jwi" "Weekly Journal Entry" plain
           (file+function+headline "~/Sync/org/weekly_journal.org" org-reverse-datetree-goto-date-in-file "Weekly Plan")
           "\n %?"
           )

```

i basically want to see previous stuff in the buffer while capturing but capture narrow down and i cannot see previous stuff that why i want to target a heading so it may show stuff previously under that in capture buffer

**Comment by akirak** [comment]
AFAIK, there is no `file+function+headline` target supported by org-capture. 

For your use case, you can create a new entry with the following template:

```
* Weekly Plan
%?
```

or add "Weekly Plan" to `org-reverse-datetree-level-formats` variable in the buffer if you want to append a content to the same entry multiple times.

**Comment by Aneeqasif** [comment]
> AFAIK, there is no `file+function+headline` target supported by org-capture. 
> 
> For your use case, you can create a new entry with the following template:
> 
> ```
> * Weekly Plan
> %?
> ```
> 
> or add "Weekly Plan" to `org-reverse-datetree-level-formats` variable in the buffer if you want to append a content to the same entry multiple times.

but if i use this capture template more then once it will add multiple copies of * weekly plan heading and i just want to append that heading in multiple captures with ability to see whats already there in capture buffer. i hope have made it a bit more clear this time

**Comment by akirak** [comment]
You can use the following function in `file+function`:

```
(defun my-org-goto-weekly-plan ()
  (org-reverse-datetree-goto-date-in-file)
  (or (re-search-forward (format org-complex-heading-regexp-format "Weekly Plan")
                         (save-excursion
                           (org-end-of-subtree))
                         t)
      (progn
        (goto-char (org-entry-end-position))
        (org-insert-subheading nil)
        (insert "Weekly Plan"))))
```

**Comment by Aneeqasif** [comment]
thanks 😊. I will try it out.

**Comment by Aneeqasif** [comment]
actually sir i am doing some hacky stuff that is causing me trouble your code works fine but when i use following functions something odd is happening

```elisp

(defun my-format-week-within-month (time)
  "Format the week number within the month for a given TIME."
  (let* ((day (nth 3 (decode-time time)))
         (month (nth 4 (decode-time time)))
         (month-name (format-time-string "%B" time))
         (week-number (+ 1 (/ (- day 1) 7))))
    (format "%d%s Week "
            week-number
            (cond ((= week-number 1) "st")
                  ((= week-number 2) "nd")
                  ((= week-number 3) "rd")
                  (t "th"))
            )))

(setq-default org-reverse-datetree-level-formats
              '("%Y"                        ; year
                "%B-%m"                     ; month
                (lambda (time) (my-format-week-within-month time)) ; week
                "%Y-%m-%d %A"))                          ; date

```

and my capture template is 
```elisp
 ("jw" "weekly Journal")
          ("jwi" "Weekly Journal Entry" plain
           (file+function "~/Sync/org/weekly_journal.org"  my-org-goto-weekly-plan )
           "\n %?"
           )
```


with this i am getting following as result in my datetree

```
* 2024

** July-07

*** 2nd Week 

**** 2024-07-09 Tuesday
*** 2nd Week 

**** 2024-07-09 Tuesday

**** Weekly Plan
 for forth time : 4
*** 2nd Week 

**** 2024-07-09 Tuesday

**** Weekly Plan
 recording 3rd time : 3
*** 2nd Week 

**** 2024-07-09 Tuesday

***** Weekly Plan
 hi there : 1

**** Weekly Plan
 hi there again : 2

```

and i want something like following 

```
* 2024

** July-07

*** 2nd Week 

1st capture 
2nd capture
3rd capture and soo on
```

I can get rid of date by removing its relevent formatting from the `org-reverse-datetree-level-formats` but i donot know why there is repetition happening do you get any clue behind the behavior?

**Comment by Aneeqasif** [comment]
replying to my own issue i got it kindda fixed by updating the fuction like
```elisp
(defun my-format-week-within-month (time)
  "Format the week number within the month for a given TIME."
  (let* ((day (nth 3 (decode-time time)))
         (week-number (+ 1 (/ (- day 1) 7))))
    (format "%d%s Week"
            week-number
            (cond ((= week-number 1) "st")
                  ((= week-number 2) "nd")
                  ((= week-number 3) "rd")
                  (t "th")))))

```

**Comment by Aneeqasif** [comment]
But still i cannot see the previous stuff under that week in the capture buffer the capture buffer just narrow down to a line and dont show anything else
as shown in ss
![image](https://github.com/akirak/org-reverse-datetree/assets/78728701/95e45667-1743-4819-9107-b4ac67202b1a)

**Comment by Aneeqasif** [comment]
ok i should delete the previous messages but ig i should leave them for history.

i got the required behaviour with  `:unnarrowed t` in the capture template but there is one last issue that i think i will need help for 

---

the issue is if i abort a capture then it removes a \n newline thats already there separating the heading and the previous capture 

### Before

![image](https://github.com/akirak/org-reverse-datetree/assets/78728701/1b27df30-0d05-4959-af8b-91555cb8fcab)

### After
recording the 3rd  capture and aborting the capture with `C-c C-k` in capture buffer 
![image](https://github.com/akirak/org-reverse-datetree/assets/78728701/c6c26b99-a1e0-485c-aa45-65f1aa3c6b69)

**Comment by akirak** [comment]
There is `:empty-lines-before` option in `org-capture-templates`. Does it solve your issue? 

I can't ensure precise behavior on this. Tweak the function to your needs.

**Comment by Aneeqasif** [comment]
nope it donot fix the issu ebut ,  if donot use plain in capture buffer it get fixed  like if i use item or checkitem

**Comment by Aneeqasif** [comment]
i think i should work on a org-journal alternative package that use datetrees for journaling

**Comment by Aneeqasif** [comment]
thanks for reading my  nonsensical messages ig its time to close the issue.
