### ISSUE TITLE
Can I make daily heading more informational?

### ISSUE THREAD

**Issue by Yatogaii** [akirak/org-reverse-datetree#67]
Thank you for create such an amazing package!

How can I store more information in daily heading?

Current Daily heading is like that:
![image](https://github.com/user-attachments/assets/e9e12946-b5d9-4e6c-9ebf-03dcc7f66105)

But I think it maybe not that informational sometimes, you must open the daily heading to see what you have done in that day.

Is there a way I can turn daily heading format to this?
![image](https://github.com/user-attachments/assets/c2e22b0c-b988-4ec2-b124-0dc7645dc369)

I'm not good both at English and elisp, if there is any offense, sorry!

**Comment by akirak** [comment]
Hello, the feature you've requested is not officially supported right now, and I don't plan to implement it in the foreseeable future.

However, you could use a hack to produce an output like that.

1. Change the date tree format to a "week-only" one (without day):

```elisp
(setq org-reverse-datetree-level-formats
      '("%Y"
        "%Y-%m"
        "%Y-%m %U"))
```

2. Set up an `org-capture` template with a function returning a template body containing the date in its heading:

```elisp
(defun my-org-capture-entry-withdate ()
  (format "* %s %%?" (format-time-string "%Y-%m-%d %a")))

(setq org-capture-templates
      '(("c" "Date tree"
         entry
         (file+function "~/org/datetree.org" org-reverse-datetree-goto-date-in-file)
         (function my-org-capture-entry-withdate))))
```

Note that some of the features of this package may not work with this setup. It is a hack, so use it at your own risk.

**Comment by Yatogaii** [comment]
Thank you for your advice, I’ll try!





------------------ Original ------------------
From: Akira Komamura ***@***.***&gt;
Date: Wed, Sep 4, 2024 10:32 PM
To: akirak/org-reverse-datetree ***@***.***&gt;
Cc: Yatogaii ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [akirak/org-reverse-datetree] Can I make daily heading moreinformational? (Issue #67)





 
Hello, the feature you've requested is not officially supported right now, and I don't plan to implement it in the foreseeable future.
 
However, you could use a hack to produce an output like that.
  
Change the date tree format to a "week-only" one (without day):
  (setq org-reverse-datetree-level-formats       '("%Y"         "%Y-%m"         "%Y-%m %U"))
  
Set up an org-capture template with a function returning a template body containing the date in its heading:
  (defun my-org-capture-entry-withdate ()   (format "* %s %%?" (format-time-string "%Y-%m-%d %a"))) (setq org-capture-templates       '(("c" "Date tree"          entry          (file+function "~/org/datetree.org" org-reverse-datetree-goto-date-in-file)          (function my-org-capture-entry-withdate))))
 
Note that some of the features of this package may not work with this setup. It is a hack, so use it at your own risk.
