### ISSUE TITLE
Day only?

### ISSUE THREAD

**Issue by mochar** [akirak/org-reverse-datetree#69]
Ive been using year -> month -> day for a while now but find no benefit in this. If I want a sparser view I just use org-sparse-tree. So I was wondering if I can completely flatten the structure to just one level, with format eg `2024-12-12 Monday`. I cannot find this back in the documentation or functions, is this possibe? Thanks so much!

**Comment by akirak** [comment]
You can set `org-reverse-datetree-level-formats` to a singleton list:

```emacs-lisp
(setq-default org-reverse-datetree-level-formats '("%Y-%m-%d %A"))
```

> find no benefit in this

You might be right. Date trees are a built-in feature of `org-capture` and `org-archive`, but I am not sure if it is necessary. It is just a way to enforce ordering of entries.

**Comment by mochar** [comment]
Totally works! Thanks a million.

> You might be right. Date trees are a built-in feature of org-capture and org-archive, but I am not sure if it is necessary. It is just a way to enforce ordering of entries.

I think its nice sometimes for navigational purposes when you're digging through your old notes. But I make most of my notes in the journal and tag them so retrieval is easy. 

Maybe I will be unhappy with this flat structure and go back, will let you know :-)
