### ISSUE TITLE
[bug] org-mode file buffer becomes disorganized after capture with org-reverse-datetree-goto-date-in-file

### ISSUE THREAD

**Issue by r-medina** [akirak/org-reverse-datetree#9]
after i do an org capture

```emacs-lisp
("m" "must do" entry (file+function "me.org" org-reverse-datetree-goto-date-in-file)
 "* MUST %^{task}\n  SCHEDULED: %t\n  %U%?\n")
```

my buffers get really disorganized

before a capture:
<img width="843" alt="Screen Shot 2020-10-21 at 1 13 41 PM" src="https://user-images.githubusercontent.com/2060940/96772064-ce7da280-139f-11eb-8e3c-f11a4372b311.png">

after a capture:
<img width="848" alt="Screen Shot 2020-10-21 at 1 14 04 PM" src="https://user-images.githubusercontent.com/2060940/96772103-dd645500-139f-11eb-9a40-39ea07750614.png">

i basically have to close the file entirely and reopen it to get it working again

i have no intuition for what is going on, but would love to figure out how to get it to stop happening if possible

**Comment by akirak** [comment]
Thank you for reporting this issue.

By "disorganized", do you mean the folding state is changed in your org buffer? If so, it is a limitation of the current implementation. It's nondeterministic about folding states and doesn't ensure preserving it during operation. I feel sorry about that. Maybe I'll have to find out a better implementation. Pressing `<backtab>` should make all trees visible again.

If `org-reverse-datetree` destroys contents, e.g. deleting some existing trees, in your precious Org files, then it is a bug. Could you please describe the issue in more detail?

**Comment by r-medina** [comment]
Sorry for not being clear!

It only affects the tree folding - not the actual contents

And it's only the trees after the insertion

**Comment by akirak** [comment]
I've made a slight change which could possibly change the behaviour, which is available in `fix/use-markers-for-save-outline-visibility` branch. Does it work?

**Comment by r-medina** [comment]
thank you, @akirak - seems to have done the trick!

**Comment by r-medina** [comment]
let me know when/if that makes it into master

**Comment by akirak** [comment]
Thanks, merged.
